VIA_ENABLE = yes
VIAL_ENABLE = yes

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MAGIC_ENABLE = yes
GRAVE_ESC_ENABLE = yes
NKRO_ENABLE = yes

PERMISSIVE_HOLD = yes
TAP_HOLD_DECISION = HOLD_ON_OTHER_KEY_PRESS
OS_DETECTION_ENABLE = yes

# To reduce firmware size
LTO_ENABLE = yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
# CONSOLE_ENABLE = yes